blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬  Ask a question
    url: https://discord.gg/4QuwYACDRX
    about: We use Discord to provide help and support for Krypton to those who need it. If you aren't sure about something, have a question, or you just want a chat, Discord is the place to go. We'd love to see you there!